src/Entity/Widget/Widget.php
<?php

namespace Score\CmsBundle\Entity\Widget;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Score\BaseBundle\Entity\BaseEntity;
use Score\CmsBundle\Entity\Widget\WidgetValue;

/**
 * @ORM\Entity()
 * @ORM\Table(name="cms_widget")
 * @ORM\HasLifecycleCallbacks()
 */
class Widget extends BaseEntity {

    /**
     * @ORM\OneToMany(targetEntity=WidgetValue::class, mappedBy="widget")
     * @ORM\OrderBy({"createdAt"="ASC"})
     */
    protected $widgetValues;


    /**
     * @ORM\Column(name="w_code", type="string", length=255, unique=true)
     */
    protected $code;

    /**
     * @ORM\Column(name="w_name", type="string", length=500, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(name="w_pattern", type="text", nullable=true)
     */
    protected $pattern = "[]";

    /**
     * @ORM\Column(name="w_template", type="text", nullable=true)
     */
    protected $template;


    public function __construct()
    {
        $this->widgetValues = new ArrayCollection();
    }


    /**
     * @return Collection<int, WidgetValue>
     */
    public function getWidgetValues(): Collection
    {
        return $this->widgetValues;
    }

    public function addWidgetValue(WidgetValue $widgetValue): self
    {
        if (!$this->widgetValues->contains($widgetValue)) {
            $this->widgetValues[] = $widgetValue;
            $widgetValue->setWidget($this);
        }

        return $this;
    }

    public function removeWidgetValue(WidgetValue $widgetValue): self
    {
        if ($this->widgetValues->removeElement($widgetValue)) {
            // set the owning side to null (unless already changed)
            if ($widgetValue->getWidget() === $this) {
                $widgetValue->setWidget(null);
            }
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPattern(): ?string
    {
        return $this->pattern;
    }

    public function setPattern(?string $pattern): self
    {
        $this->pattern = $pattern;

        return $this;
    }

    public function getPatternArr(): ?array
    {
        return json_decode($this->pattern, true);
    }

    public function setPatternArr(?array $pattern): self
    {
        $this->pattern = json_encode($pattern);

        return $this;
    }

    public function getTemplate(): ?string
    {
        return $this->template;
    }

    public function setTemplate(?string $template): self
    {
        $this->template = $template;

        return $this;
    }
}

src/Entity/Widget/WidgetValue.php
<?php

namespace Score\CmsBundle\Entity\Widget;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Score\BaseBundle\Entity\BaseEntity;
use Score\CmsBundle\Entity\Widget\Widget;

/**
 * @ORM\Entity()
 * @ORM\Table(name="cms_widget_value")
 * @ORM\HasLifecycleCallbacks()
 */
class WidgetValue extends BaseEntity {

    
    /**
     * @ORM\ManyToOne(targetEntity=Widget::class, inversedBy="widgetValues")
     */
    protected $widget;

    /**
     * @ORM\Column(name="w_code", type="string", length=255)
     */
    protected $code;

    /**
     * @ORM\Column(name="w_name", type="string", length=500, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(name="w_note", type="string", length=1000, nullable=true)
     */
    protected $note;

    /**
     * @ORM\Column(name="w_data", type="text", nullable=true)
     */
    protected $data;

    
    public function getWidget(): ?Widget
    {
        return $this->widget;
    }

    public function setWidget(?Widget $widget): self
    {
        $this->widget = $widget;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getData(): ?string
    {
        return $this->data;
    }

    public function setData(?string $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getDataArr(): ?array
    {
        return json_decode($this->data, true);
    }

    public function setDataArr(?array $data): self
    {
        $this->data = json_encode($data);

        return $this;
    }
}

src/Form/WidgetType.php
<?php

namespace Score\CmsBundle\Form;

use Score\CmsBundle\Entity\Widget\Widget;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WidgetType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'label_format' => 'score.cms.widget.edit.%name%'
            ])
            ->add('code', null, [
                'label_format' => 'score.cms.widget.edit.%name%'
            ])
            ->add('pattern', null, [
                'label_format' => 'score.cms.widget.edit.%name%',
                'attr' => ['rows' => 20]
            ])
            ->add('template', null, [
                'label_format' => 'score.cms.widget.edit.%name%',
                'attr' => ['rows' => 20]
            ])
            ->add('visibility', null, [
                'label_format' => 'score.cms.widget.edit.%name%'
        ]);

    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Widget::class
        ));
    }

    


}

src/Resources/views/Widget/edit.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{% import "@ScoreBase/Default/macros.html.twig" as m %}

{% block content_header_title %}
	<h1>{{ 'score.cms.widget.edit.title' | trans }}</h1>
{% endblock %}

{% block content_header_breadcrumb %}
	{{ parent() }}
	<li class="active">{{ 'score.cms.widget.breadcrumb' | trans }}</li>
{% endblock %}

{% block javascripts %}
	{{ parent() }}

    <script language="Javascript" type="text/javascript" src="{{ asset('bundles/scorecms/plugins/editarea-code-r33-trunk/edit_area/edit_area_full.js') }}"></script>
	<script language="Javascript" type="text/javascript">

		// pattern
		editAreaLoader.init({
			id: "widget_pattern"	// id of the textarea to transform	
			,start_highlight: true
			,language: "sk"
			,syntax: "css"	
			,toolbar: "search, go_to_line, |, undo, redo, |, select_font, |, syntax_selection, |, change_smooth_selection, highlight, reset_highlight, |, help"
			,syntax_selection_allow: "css,html,js,php,python,vb,xml,c,cpp,sql,basic,pas,brainfuck"
			,show_line_colors: true
		});


    </script>	
	
	<script language="Javascript" type="text/javascript">

		// template
		editAreaLoader.init({
			id: "widget_template"	// id of the textarea to transform	
			,start_highlight: true
			,language: "sk"
			,syntax: "html"	
			,toolbar: "search, go_to_line, |, undo, redo, |, select_font, |, syntax_selection, |, change_smooth_selection, highlight, reset_highlight, |, help"
			,syntax_selection_allow: "css,html,js,php,python,vb,xml,c,cpp,sql,basic,pas,brainfuck"
			,show_line_colors: true
		});


    </script>

    <script>
        jQuery(function ($) {
            $( document ).ready(function() {
                // zobrazenie JSON kodu v kope alebo pekne naformatovaneho
                $('#pattern_example_btn').click(function(e) {
                  e.preventDefault();
                  let el = $('#pattern_example');
                  if (el.is("p")) {
                    el.parent().html(`<pre id="pattern_example">${el.html()}</pre>`);
                  } else {
                    el.parent().html(`<p id="pattern_example">${el.html()}</p>`);
                  }
                });
            });
        });
    </script>

{% endblock %}

{% block body %}
	{{ m.alerts() }}

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<p>
	PATTERN EXAMPLE:     <a class="" href="#" id="pattern_example_btn">Show formated</a>

  </p>
  <div>
  <p id="pattern_example">
[
    {
        "code": "title",
        "label": "Title",
        "help": "Write short title",
        "type": "text",
        "min": 7,
        "max": 25
    },{
        "code": "description",
        "label": "Description",
        "help": "Write max 350 characters",
        "type": "richtext",
        "min": 7,
        "max": 350,
        "rows": 15,
        "editor": "cke5_basic"
    },{ 
        "code": "logo", 
        "label": "Logo", 
        "type": "image"
    },{
        "code": "color",
        "label": "Color",
        "type": "choice",
        "choices": [{
              "label": "Red",
              "value": "red"
          },{
              "label": "Green",
              "value": "green"
          },{
              "label": "Blue",
              "value": "blue"
        }]
    }
]
</p>
</div>
<p>
 Type can by one of [text, choice, image, textarea, richtext]. First richtext can specify editor.
</p>
<p> Check valid json at <a target="_blanc" href="https://jsoneditoronline.org/">jsoneditoronline.org</a>.</p>

	<input class="btn btn-primary" type="submit" value="{{ 'score.cms.widget.edit.save' | trans }}"/>
	{{ form_end(form) }}


<p>
	<br><a class="" href="{{ path('score-cms-widget-value-new',{widgetId:entity.id ?: 0}) }}">{{ 'score.cms.widget.value.new'|trans }}</a>
</p>
{% endblock %}

src/Resources/views/Widget/edit_value.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{% import "@ScoreBase/Default/macros.html.twig" as m %}

{% block content_header_title %}
	<h1>{{ 'score.cms.widget.edit.title' | trans }}: {{entity.code}}</h1>
{% endblock %}

{% block content_header_breadcrumb %}
	{{ parent() }}
	<li class="active">{{ 'score.cms.widget.breadcrumb' | trans }}</li>
	<li class="active"><a class="" href="{{ path('score-cms-widget-value-list', {'id': widget.id }) }}">{{ widget.name }}</a></li>
{% endblock %}

{% block javascripts %}
	{{ parent() }}

{% endblock %}

{% block body %}
	{{ m.alerts() }}

	{{ form_start(form) }}
	{{ form_widget(form) }}

	<input class="btn btn-primary" type="submit" value="{{ 'score.cms.widget.edit.save' | trans }}"/>

	{{ form_end(form) }}

{% endblock %}

src/Resources/views/Widget/list.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{% import "@ScoreBase/Default/macros.html.twig" as m %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.css') }}" rel="stylesheet"/>
{% endblock %}

{% block content_header_title %}
    <h1>{{ 'score.cms.widget.list.topTitle'|trans }} </h1>
{% endblock %}

{% block content_header_breadcrumb %}
    {{ parent() }}
    <li class="active">{{ 'score.cms.widget.breadcrumb' | trans }}</li>
{% endblock %}

{% block body %}

    {{ m.alerts() }}


    <div class="row">
        <div class="col-sm-10">

            <div class="box box-solid">
                <div class="box-body">
                    <table id="widgets-datatable" class="table table-striped display compact">
                        <thead>
                            <tr>
                                <th>{{ 'score.cms.widget.list.name'|trans  }}</th>
                                <th>{{ 'score.cms.widget.list.code'|trans  }}</th>
                                <th>{{ 'score.cms.widget.list.count'|trans  }}</th>
			                    {% if is_granted('ROLE_ADMIN') %}
                                    <th>{{ 'score.cms.widget.list.action'|trans  }}</th>
			                    {% endif %}			
                            </tr>
                        </thead>
                        <tbody>
                        {% for widget in widgets %}
                            <tr>
                                <td>
                                    <a class="" href="{{ path('score-cms-widget-value-list',{id:widget.id}) }}">{{ widget.name }}</a>
                                </td>
                                <td>
                                    {{ widget.code }}
                                </td>                                
                                <td>
                                    {{ widget.widgetValues | length }}
                                </td>
			                    {% if is_granted('ROLE_ADMIN') %}
                                    <td>
                                        <a class="" href="{{ path('score-cms-widget-edit',{id:widget.id}) }}">{{ 'score.cms.widget.list.edit' | trans }}</a>
                                        <br><a class="" href="{{ path('score-cms-widget-value-new',{widgetId:widget.id}) }}">{{ 'score.cms.widget.value.new'|trans }}</a>
                                        <br><a class="delete-widget" href="{{ path('score-cms-widget-delete',{id:widget.id}) }}">{{ 'score.cms.widget.list.delete'|trans }}</a>
                                    </td>
			                    {% endif %}			
                            </tr>
                        {% endfor %}
                        </tbody>                      
                    </table>
                </div>
                <div class="box-footer clearfix">

                </div>
            </div>
        </div>
        <div class="col-sm-2">
            {% if is_granted('ROLE_ADMIN') %}
                <div class="box box-primary">
                    <div class="box-body">
                        <a class="btn btn-primary" href="{{ path('score-cms-widget-new')}}">{{ 'score.cms.widget.list.new'|trans }}</a>
                    </div>
                </div>
            {% endif %}			
        </div>
    </div>

    {{ include('@ScoreCms/Default/_delete_modal.html.twig') }}

{% endblock %}


    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('bundles/scorecms/plugins/jQueryUI/jquery-ui.min.js') }}"></script>
        <script src="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.js') }}"></script>
        <script type="text/javascript">

            $('#widgets-datatable').DataTable({
            // "processing": true,
            // "serverSide": true,
            // "paging": true,
            // "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
             "pageLength": 50,
              'language': {
                    url: '/bundles/scorecms/plugins/datatables/sk.js'
                }
        });



        </script>

        <script>

            $('body').on('click', '.delete-widget', function (e) {
                e.preventDefault();
                $('#confirm-delete-cms-item-modal .cms-confirm-delete').attr('href', $(this).attr('href'));
                $('#confirm-delete-cms-item-modal .modal-body > p').html("{{ "score.alert.widget.delete" |trans }}");
                $('#confirm-delete-cms-item-modal').modal('show');
            });
        </script>
    {% endblock %}

src/Resources/views/Widget/update_data.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{# {% extends 'base.html.twig' %} #}
{% import "@ScoreBase/Default/macros.html.twig" as m %}

{% block content_header_title %}
	<h1>{{ 'score.cms.widget.edit.title' | trans }}</h1>
{% endblock %}

{% block content_header_breadcrumb %}
	{{ parent() }}
	<li >{{ 'score.cms.widget.breadcrumb' | trans }}</li>
	<li class="active"><a class="" href="{{ path('score-cms-widget-value-list', {'id': widget.id }) }}">{{ widget.name }}</a></li>
{% endblock %}

{% block javascripts %}
	{{ parent() }}

	{% for el in widget.patternArr | filter(v => v.type is same as "richtext") %}
	     {{m.cmsEditorJs(el.code, el.editor is defined ? el.editor : "cke5_simple")}}
	{% endfor %}

	<script>
		//  Image - spracovavanie pre type image
		$('.image-input-wrapper').each(function(){
			let hidden = $(this).find('input[type="hidden"]')
			let img = $(hidden?.val() || "<img>");
			$(this).find('input[type="text"]').each(function(){
				$(this).val(img.attr(this.dataset.part));
			}).on('input', function(){
				img.attr(this.dataset.part, $(this).val())
				hidden.val(img.wrap("<p/>").parent().html())
        	});
        });
	</script>
	{{ include('@ScoreCms/Default/_js_keyboard_submit_form.html.twig', {"formSelector": "form.main-body-form"}) }}

{% endblock %}

{% block body %}
	{{ m.alerts() }}

	<div>
		<h2>{{value.name}}</h2>
		<p>{{value.note}}</p>
	</div>
	<form method="post" class="main-body-form">
		{% for k,v in widget.patternArr %}
			{% if v.type is same as "text" %}
				<div class="form-group">
					<label class="control-label" for="{{ v.code }}">{{v.label}}</label>
					<input class="form-control" name="widget[{{ v.code }}]" id="{{ v.code }}" type="text"  
							minlength="{{ v.min is defined ? v.min }}" maxlength="{{ v.max is defined ? v.max }}" {{v.required is defined and v.required ? "required"}} 
							value="{{ value.dataArr[v.code] is defined ? value.dataArr[v.code] : ""}}" >
					<small class="form-text text-muted">{{ v.help is defined ? v.help }}</small>
				</div>
			{% elseif v.type is same as "choice" %}
				<div class="form-group">
					<label for="{{ v.code }}">{{v.label}}</label>
					<select class="form-control" name="widget[{{ v.code }}]" id="{{ v.code }}" >
						{% for ch in v.choices %}
							<option value="{{ ch.value }}" {{ value.dataArr[v.code] is defined and value.dataArr[v.code] is same as ch.value ? "selected"}}>{{ ch.label }}</option>
						{% endfor %}
					</select>
					<small>{{ v.help is defined ? v.help }}</small>
				</div>
			{% elseif v.type is same as "image" %}
				<div class="form-group image-input-wrapper">
					<label for="{{ v.code }}-src">{{v.label}} URL</label>
					<input class="form-control" id="{{ v.code }}-src" data-part="src" type="text" value="" >
					<label for="{{ v.code }}-alt">{{v.label}} Alt text</label>
					<input class="form-control" id="{{ v.code }}-alt" data-part="alt" type="text"  value="" >
					<input name="widget[{{ v.code }}]" id="{{ v.code }}" type="hidden"  value="{{ value.dataArr[v.code] is defined ? value.dataArr[v.code] : "" }}" >
					<small>{{ v.help is defined ? v.help }}</small>
				</div>
			{% elseif v.type is same as "textarea" or v.type is same as "richtext" %}
				<div class="form-group">
					<label for="{{ v.code }}">{{v.label}}</label>
					<textarea class="form-control" name="widget[{{ v.code }}]" id="{{ v.code }}" minlength="{{ v.min is defined ? v.min }}" maxlength="{{ v.max is defined ? v.max }}" rows="{{ v.rows is defined ? v.rows }}" >{{ value.dataArr[v.code] is defined ? value.dataArr[v.code] : "" }}</textarea>
					<small>{{ v.help is defined ? v.help }}</small>
				</div>
			{% else %}
				<p>nothing to show</p>
			{% endif %}
		{% else %}
			<p>nothing to edit</p>
		{% endfor %}
		<input class="btn btn-primary" name="widget_submited" type="submit" value="{{ 'score.cms.widget.edit.save' | trans }}" />
	</form>

{% endblock %}

src/Resources/views/Widget/values_list.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{% import "@ScoreBase/Default/macros.html.twig" as m %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.css') }}" rel="stylesheet"/>
{% endblock %}

{% block content_header_title %}
    <h1>{{ 'score.cms.widget.list.topTitle'|trans }} </h1>
{% endblock %}

{% block content_header_breadcrumb %}
    {{ parent() }}
    <li class="active">{{ 'score.cms.widget.breadcrumb' | trans }}</li>
{% endblock %}

{% block body %}

    {{ m.alerts() }}


    <div class="row">
        <div class="col-sm-10">

            <div class="box box-solid">
                <div class="box-body">
                    <table id="widget-value-datatable" class="table table-striped display compact">
                        <thead>
                            <tr>
                                <th>
                                    {{ 'score.cms.widget.list.name'|trans  }}
                                </th>
                                <th>{{ 'score.cms.widget.list.code'|trans  }}</th>
			                    <th>
                                    {% if is_granted('ROLE_ADMIN') %}{{ 'score.cms.widget.list.action'|trans  }}{% endif %}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for value in values %}
                            <tr>
                                <td>
                                    <a class="" href="{{ path('score-cms-widget-update-data',{id:value.id, widgetId: widgetId}) }}">{{ value.name }}</a>
                                </td>
                                <td>
                                    {{ value.code }}
                                </td>
                                <td>
                                    <a class="" href="{{ path('score-cms-widget-value-edit',{id:value.id, widgetId: widgetId}) }}">{{ 'score.cms.widget.list.edit'|trans }}</a>
			                        {% if is_granted('ROLE_ADMIN') %}
                                        <br><a class="delete-widget-value" href="{{ path('score-cms-widget-value-delete',{id:value.id, widgetId: widgetId}) }}">{{ 'score.cms.widget.list.delete'|trans }}</a>
			                        {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                      
                    </table>
                </div>
                <div class="box-footer clearfix">

                </div>
            </div>
        </div>
        <div class="col-sm-2">
            {% if is_granted('ROLE_ADMIN') %}
                <div class="box box-primary">
                    <div class="box-body">
                        <a class="btn btn-primary" href="{{ path('score-cms-widget-value-new',{widgetId: widgetId}) }}">{{ 'score.cms.widget.value.new'|trans }}</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


    {{ include('@ScoreCms/Default/_delete_modal.html.twig') }}

{% endblock %}


    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('bundles/scorecms/plugins/jQueryUI/jquery-ui.min.js') }}"></script>
        <script src="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.js') }}"></script>
        <script type="text/javascript">

            $('#widget-value-datatable').DataTable({
             "pageLength": 50,
              'language': {
                    url: '/bundles/scorecms/plugins/datatables/sk.js'
                }
        });

        </script>

        <script>

            $('body').on('click', '.delete-widget-value', function (e) {
                e.preventDefault();
                $('#confirm-delete-cms-item-modal .cms-confirm-delete').attr('href', $(this).attr('href'));
                $('#confirm-delete-cms-item-modal .modal-body > p').html("{{ "score.alert.widget.value.delete" |trans }}");
                $('#confirm-delete-cms-item-modal').modal('show');
            });
        </script>
    {% endblock %}