src/Entity/Option.php
<?php

namespace Score\CmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


use Score\BaseBundle\Entity\BaseEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="cms_option")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"code"},
 *     message="option.code.unique"
 * )
 */
class Option extends BaseEntity
{
    /**
     * @ORM\Column(name="code", type="string", length=255, nullable=true, unique=true)
     */
    protected $code;

    /**
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(name="value", type="text", nullable=true)
     */
    protected $value;

    
    /**
     * @ORM\Column(name="o_params", type="text", nullable=true)
     */
    protected $params = "[]";

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(?string $value): self
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Get the value of name
     */ 
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of name
     *
     * @return  self
     */ 
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }
    
    public function getParams(): ?string
    {
        return $this->params;
    }

    public function setParams(?string $params): self
    {
        $this->params = $params;

        return $this;
    }

    public function getParamsArr(): ?array
    {
        return json_decode($this->params, true);
    }

    public function setParamsArr(?array $params): self
    {
        $this->params = json_encode($params);

        return $this;
    }
}

src/Controller/Article/PublicController.php
<?php

namespace Score\CmsBundle\Controller\Article;

use Score\CmsBundle\Entity\Article\Article;
use Score\BaseBundle\Services\Pager;
use Doctrine\ORM\EntityManagerInterface;
use Score\CmsBundle\Services\StatManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/clanky")
 */
class PublicController extends AbstractController {

    /**
     * @Route("/", name="score_public_articles_list", methods={"GET"})
     */
    public function listAction(Request $request, EntityManagerInterface $entityManager, Pager $pager): Response {
        $repo = $entityManager->getRepository(Article::class);
        $page = $request->get('p', 1);
        $pageSize = $request->get('size', 6);
        $articles = $repo->findArticlesByPage(['page' => $page, 'pageSize' => $pageSize], ['visible' => true]);
        $articleList = array_chunk($articles['list'], 3);

        $pager->setUrl($request->getUri());
        $pager->setItemsPerPage($pageSize);
        $pager->setCount($articles['total']);
        $pager->setPage($page);
        $pager->getPages();


        return $this->render('@ScoreCms/Public/default/article_list.html.twig', [
            'articleList' => $articleList,
            'pager' => $pager,
        ]);
    }

    /**
     * @Route("/{slug}", name="score_public_articles_detail", methods={"GET"})
     */
    public function detailAction(EntityManagerInterface $entityManager, $slug = null): Response {
        $repo = $entityManager->getRepository(Article::class);
        $article = $repo->findOneBy([
            'slug' => $slug,
            'published' => 1,
//            'isDeleted' => false
        ]);
        $responseCode = 200;
        if (!$article || $article->getIsDeleted()) {
            $article = new Article();
            $article->setName('404');
            $article->setBody('Tento článok sa tu nenachádza');
            $responseCode = 404;
        }
        $topArticles = $repo->findSidebarArticles($article);
        return new Response($this->renderView('@ScoreCms/Public/default/article_detail.html.twig', [
            'article' => $article,
            'articles' => $topArticles,
        ]), $responseCode);
    }


}

src/Controller/DefaultController.php
<?php

namespace Score\CmsBundle\Controller;


use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Score\BaseBundle\Services\SeoUrl;
use Score\CmsBundle\Services\ImageManager;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;

class DefaultController extends AbstractController
{

    /**
     * @Route("/admin/start", name="admin_start")
     */
    public function dashboardAction()
    {
        return $this->render('@ScoreCms/Default/start.html.twig', array(

        ));

        //return $this->redirect($this->generateUrl('user'));
        //return $this->render('ScoreCmsBundle:Default:dashboard.html.twig');
    }


}

src/Controller/Event/PublicController.php
<?php

namespace Score\CmsBundle\Controller\Event;

use Score\BaseBundle\Services\Pager;
use Score\CmsBundle\Entity\Event\Event;
use Doctrine\ORM\EntityManagerInterface;
use Score\CmsBundle\Services\StatManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/udalosti")
 */
class PublicController extends AbstractController {


    /**
     * @Route("/", name="score_public_event_list", methods={"GET"})
     */
    public function listAction(Request $request, EntityManagerInterface $entityManager, StatManager $statManager, Pager $pager): Response {
        $repo = $entityManager->getRepository(Event::class);
        $page = $request->get('p', 1);
        $pageSize = $request->get('size', 6);
        $events = $repo->findEventsByPage(array('page' => $page, 'pageSize' => $pageSize), ['visible' => true]);
        $eventList = array_chunk($events['list'], 3);
        $pager->setUrl($request->getUri());
        $pager->setItemsPerPage($pageSize);
        $pager->setCount($events['total']);
        $pager->setPage($page);
        $pager->getPages();

        return $this->render('@ScoreCms/Public/default/event_list.html.twig', [
            'eventList' => $eventList,
            'pager' => $pager,
        ]);
    }

    /**
     * @Route("/{slug}", name="score_public_events_detail", methods={"GET"})
     */
    public function detailAction(EntityManagerInterface $entityManager, StatManager $statManager, $slug = null): Response {
        $repo = $entityManager->getRepository(Event::class);
        $event = $repo->findOneBy([
            'slug' => $slug,
            'published' => 1,
//            'isDeleted' => false
        ]);
        $responseCode = 200;
        if (!$event || $event->getIsDeleted()) {
            $event = new Event();
            $event->setName('404');
            $event->setContent('Táto udalosť sa tu nenachádza');
            $responseCode = 404;
        }

        $topEvents = $repo->findSidebarEvents($event);
        return new Response($this->renderView('@ScoreCms/Public/default/event_detail.html.twig', [
            'event' => $event,
            'events' => $topEvents,
        ]), $responseCode);
    }


}

src/Controller/Gallery/PublicController.php
<?php

namespace Score\CmsBundle\Controller\Gallery;

use Score\CmsBundle\Entity\Gallery\Gallery;
use Score\CmsBundle\Entity\Gallery\GalleryImage;
use Score\CmsBundle\Services\ImageManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Contracts\Translation\TranslatorInterface;

class PublicController extends AbstractController
{

    /**
     * @Route("/api/gallery-load/{id}", name="cms_api_gallery_load")
     */
    public function loadAction(Request $request, TranslatorInterface $translator, $id)
    {
        header('Access-Control-Allow-Origin: *');

        // TODO then disable for localhost!
        $isAdmin = $request->headers->get('referer') && str_contains($request->headers->get('referer'), '/admin/gallery/'); // editovanie, example

        $em = $this->getDoctrine()->getManager();
        //$gallery = $em->getRepository(Gallery::class)->find($id);
        $gallery = $em->getRepository(Gallery::class)->findOneByIdentifier($id);

        // ak neexistuje alebo nieje verejny (cez zapor)
        if (!($gallery && ($gallery->getVisibility() || $isAdmin))) {
            return new JsonResponse([
                "status" => "error",
                "message" => $translator->trans("score.cms.gallery.error.loadData")
            ]);
        }

        $data = [
            //"ref" => $request->headers->get('referer'),
            "galleryId" => $gallery->getIdentifier(),
            "identifier" => $gallery->getIdentifier(),
            "name" => $gallery->getName(),
            "description" => $gallery->getDescription(),
            "isActive" => $gallery->getIsActive(),
            "endMessage" => $gallery->getEndMessage(),
            "visibility" => $gallery->getVisibility(),
            "type" => $gallery->getType(),
            "params" => $gallery->getParamsArr(),
            "galleryDir" => $this->getParameter('cms_gallery_dir'), //. '/' . $gallery->getIdentifier(),
            "imageStrategy" => $this->getParameter('cms_gallery_image_strategy'),
            "imageSubDirs" => $this->getParameter('cms_gallery_subdirs'),
            "images" => []
        ];

        foreach ($gallery->getImages() as $image) {
            if (($image->getVisibility() && $image->getIsActive()) || $isAdmin)
                $data["images"][] = [
                    "galleryId" => $gallery->getIdentifier(),
                    "identifier" => $image->getIdentifier(),
                    "name" => $image->getName(),
                    "description" => $image->getDescription(),
                    "sortOrder" => $image->getSortOrder(),
                    "isActive" => $image->getIsActive(),
                    "size" => $image->getSize(),
                    "extension" => $image->getExtension(),
                    "filename" => $image->getOriginalFilename(),
                    "x" => $image->getParamsArr()["x"],
                    "y" => $image->getParamsArr()["y"],
                    "ratio" => $image->getParamsArr()["ratioOrig"],
                ];
        }

        usort($data["images"], function ($a, $b) {
            return $a['sortOrder'] <=> $b['sortOrder'];
        });

        return new JsonResponse([
            'status' => "ok",
            "data" => $data
        ]);
    }



    /**
     * @Route("/file/g/{galleryId}/{imageId}-{size}.{ext}", name="cms-gallery-load-file")
     */
    public function fileAction(Request $request, ImageManager $imageManager, $galleryId, $imageId, $size, $ext)
    {

        //header('Access-Control-Allow-Origin: *');
        $previews = $this->getParameter('cms_gallery_subdirs')["preview"];
        $closest = null;
        foreach ($previews  as $s)
            if (!$closest && $s >= $size)
                $closest = "preview/$s";
        if (!$closest)
            $closest = "preview/" . $previews[count($previews) - 1];

        $strategy = $this->getParameter('cms_gallery_image_strategy');

        // basic simulation of loading time delay (3sec pri 1920)
        //sleep(3*$size/1920);

        $em = $this->getDoctrine()->getManager();
        $image = $em->getRepository(GalleryImage::class)->findOneByIdentifier($imageId);


        if ($image) {
            if ($strategy === 'redirect') { // redirect
                return $this->redirect($this->getParameter('cms_gallery_dir') . "/$galleryId/$closest/$imageId.$ext");
            } elseif ($strategy === 'open') { // open
                $filePath = $this->getParameter('cms_gallery_upload_dir') . "/$galleryId/$closest/$imageId.$ext";
                return new BinaryFileResponse($filePath);
            } else { // create
                //$closest = "preview/".$previews[count($previews) - 1];
                $filePath = $this->getParameter('cms_gallery_upload_dir') . "/$galleryId/$closest/$imageId.$ext";

                // Metoda vrati hotovu odpoved vykresli obrazok kod dalej nepokracuje (alebo aj pokracuje?)
                $file = $imageManager->createImageFrom($filePath, $size, $ext);

                $response = new Response();
                $response->headers->set('Content-Type', in_array($ext, ['png', 'gif']) ? "image/$ext" : "image/jpeg");
                $response->setLastModified($image->getCreatedAt());
                $response->setContent($file);
                $response->setPublic();
                return $response;
            }
        } else {
            return $this->redirectToRoute('default_subpage', ['seoid' => "no-file/g/$galleryId/$imageId-$size.$ext"]);
        }
    }
}
                // $response = new Response();
                // $fileName = $imageId . '-' . $size . '.' . $ext;
                // $disposition = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_INLINE, $fileName);
                // $response->headers->set('Content-Disposition', $disposition);
                // $response->headers->set('Content-Type', in_array($ext, ['png', 'gif']) ? "image/$ext" : "image/jpeg");
                // $image = $this->getDoctrine()->getManager()->getRepository(GalleryImage::class)->findOneBy(["identifier" => $imageId]);
                // $closest = "preview/".$previews[count($previews) - 1];
                // $response->setContent($file);
                // return $response;

src/Resources/views/Public/default/_accordion.html.twig
{% set accordion = cms_block_accordion(accordionId ?? 0) %}
{% if accordion %}
	<div class="govuk-accordion accordion" data-module="idsk-accordion" id="accordion_{{ accordion.id }}" data-attribute="value">
		<div class="controls d-none govuk-accordion__controls">
			<button class="govuk-accordion__open-all" data-open-title="Otvoriť všetky" data-close-title="Zatvoriť všetky" type="button" aria-expanded="false">
				<span class="govuk-visually-hidden govuk-accordion__controls-span" data-section-title="sekcie"></span>
			</button>
		</div>
        <div>
        {% for item in accordion.items %}
            <div class="accordion-item govuk-accordion__section {{ item.isOpened ? "govuk-accordion__section--expanded" : "" }}">
                <div class="govuk-accordion__section-header">
                    <h2 class="accordion-header govuk-accordion__section-heading">
                        <button class="accordion-button {{ item.isOpened ? "" : "collapsed" }} govuk-accordion__section-button" 
                            type="button" data-bs-toggle="collapse" data-bs-target="#accordion_{{ accordion.id ~ "_" ~ item.id }}-content-1" 
                            aria-expanded="{{ item.isOpened ? "true" : "false" }}" aria-controls="accordion_{{ accordion.id ~ "_" ~ item.id }}-content-1">
                            <span class="govuk-accordion__section-button" id="accordion_{{ accordion.id ~ "_" ~ item.id }}-heading-1">
                                {{ item.title }}
                            </span>
                        </button>
                    </h2>
                    <div class="summary {# d-none #} govuk-accordion__section-summary govuk-body" id="accordion_{{ accordion.id ~ "_" ~ item.id }}-summary-1">
                        {{ item.summary }}
                    </div>
                </div>
                <div id="accordion_{{ accordion.id ~ "_" ~ item.id }}-content-1" class="accordion-collapse collapse {{ item.isOpened ? "show" : "" }} govuk-accordion__section-content" aria-labelledby="accordion_{{ accordion.id ~ "_" ~ item.id }}-heading-1"  data-bs-parent="#accordion_{{ accordion.id }}">
                    <div class='accordion-body govuk-body'>
                        {{ item.content | cms_document_links | raw }}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
	</div>
{% endif %}

src/Resources/views/Public/default/_article_card_mini.html.twig
<div class="idsk-card idsk-card-secondary">
    <a href="{{ path('score_public_articles_detail',{'slug':article.slug}) }}" title="{{ article.name }}">
        <img class="idsk-card-img idsk-card-img-secondary"
            src="{{ article.iconThumb(640,480) }}"
            alt="{{ article.name }}" aria-hidden="true" width="100%">
    </a>

    <div class="idsk-card-content idsk-card-content-secondary">
        <div class="idsk-card-meta-container">
            <span class="idsk-card-meta idsk-card-meta-date">
                <a href="{{ path('score_public_articles_detail',{'slug':article.slug}) }}" class="govuk-link" title="Pridané dňa:  {{article.publishedFrom|date('d.m.Y') }}">{{article.publishedFrom|date('d.m.Y') }}</a></span>
        </div>

        <div class="idsk-heading idsk-heading-secondary">
            <a href="{{ path('score_public_articles_detail',{'slug':article.slug}) }}" class="idsk-card-title govuk-link" title="{{ article.name }}">{{ article.name }}</a>
        </div>

    </div>
</div>

src/Resources/views/Public/default/_block.html.twig
{% if blockJoint.block.visibility is same as true %}

    {% if 'static' == blockJoint.block.type %}
        <div class="static-block">{{ blockJoint.block.content | cms_document_links | raw }}</div>
    {% elseif 'html' == blockJoint.block.type %}
        <div class="html-block">{{ blockJoint.block.content | cms_widget_all | cms_text_all | cms_document_links | raw }}</div>
    {% elseif 'menu' == blockJoint.block.type %}
        {{ include('@ScoreCms/Public/default/_blockMenu.html.twig', {'menuId':blockJoint.block.paramsArr.menuId ?? 0} ) }}
    {% elseif 'form' == blockJoint.block.type %}
        <div data-cms="react-form" data-form-id="{{ blockJoint.block.paramsArr.formId ?? 0 }}"></div>
    {% elseif 'gallery' == blockJoint.block.type %}
        <div data-cms="react-gallery" data-gallery-id="{{ blockJoint.block.paramsArr.galleryId ?? 0 }}"></div>
    {% elseif 'accordion' == blockJoint.block.type %}
        {{ include('@ScoreCms/Public/default/_accordion.html.twig',{'accordionId': blockJoint.block.paramsArr.accordionId}) }}
    {% elseif 'controllerContent' == blockJoint.block.type %}
        {% if blockJoint.block.paramsArr | length %}
            {{ render(controller(blockJoint.block.module ~ '::' ~ blockJoint.block.action, blockJoint.block.paramsArr)) }}
        {% else %}
            {{ render(controller(blockJoint.block.module ~ '::' ~ blockJoint.block.action)) }}
        {% endif %}
    {% endif %}

{% endif %}

src/Resources/views/Public/default/_event_card_mini.html.twig
<div class="idsk-card idsk-card-secondary">
    <a href="{{ path('score_public_events_detail',{'slug':event.slug}) }}" title="{{ event.name }}">
        <img class="idsk-card-img idsk-card-img-secondary"
            src="{{ event.iconThumb(640,480) }}"
            alt="{{ event.name }}" aria-hidden="true" width="100%">
    </a>
    <div class="idsk-card-content idsk-card-content-secondary">
        <div class="idsk-heading idsk-heading-secondary">
            <a href="{{ path('score_public_events_detail',{'slug':event.slug}) }}" class="idsk-card-title govuk-link" title="{{ event.name }}">{{ event.name }}</a>
        </div>
    </div>
</div>

src/Resources/views/Public/default/_event_card_small.html.twig
<div class="idsk-card idsk-card-secondary">
    <a href="{{ path('score_public_events_detail',{'slug':event.slug}) }}" title="{{ event.name }}">
        <img class="idsk-card-img idsk-card-img-secondary"
            src="{{ event.iconThumb(640,480) }}"
            alt="{{ event.name }}" aria-hidden="true" width="100%">
    </a>

    <div class="idsk-card-content idsk-card-content-secondary">
       

        <div class="idsk-heading idsk-heading-secondary">
            <a href="{{ path('score_public_events_detail',{'slug':event.slug}) }}" class="idsk-card-title govuk-link" title="{{ event.name }}">{{ event.name }}</a>
        </div>

        <p class="idsk-body idsk-body-secondary">
            {{ event.teaser| cms_document_links | raw }}
        </p>
    </div>
</div>

src/Resources/views/Public/default/_header.html.twig
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('default_homepage')}}">{{app.request.host()|split('.')|filter(v => v != "www")|first|upper}}</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarsExample09">
				{{ include('@ScoreCms/Public/default/_mainMenu.html.twig') }}
				{% if search_form is defined and search_form %}
					<form action="/vyhladavanie" method="GET">
						<input class="form-control" value="{{ search_slug ?? "" }}" type="text" name="search" placeholder="{{ "cms.search" | trans}}" aria-label="{{ "cms.search" | trans}}">
					</form>
				{% endif %}
			</div>
		</div>
	</nav>

</div>

src/Resources/views/Public/default/article_block_top.html.twig
{% if bigArticle %}
    <hr class="idsk-hr-separator govuk-!-margin-bottom-6">
    <h2 class="govuk-heading-l">{{ header is defined and header ? header : "Aktuality" }}</h2>
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <div class="idsk-card idsk-card-hero">
                <a href="{{ path('score_public_articles_detail',{'slug':bigArticle.slug}) }}"
                   title="{{ bigArticle.name }}">
                    <img class="idsk-card-img idsk-card-img-hero"
                         src="{{ bigArticle.iconThumb(640,480) }}"
                         alt="{{ bigArticle.name }}" aria-hidden="true"
                         width="100%">
                </a>

                <div class="idsk-card-content idsk-card-content-hero">
                    <div class="idsk-card-meta-container">
                    <span class="idsk-card-meta idsk-card-meta-date">
                        <a href="#" class="govuk-link"
                           title="Pridané dňa: {{ bigArticle.publishedFrom|date('d.m.Y') }}">{{ bigArticle.publishedFrom|date('d.m.Y') }}</a>
                    </span>
                    </div>


                    <div class="idsk-heading idsk-heading-hero">
                        <a href="{{ path('score_public_articles_detail',{'slug':bigArticle.slug}) }}"
                           class="idsk-card-title govuk-link" title="{{ bigArticle.name }}">{{ bigArticle.name }}</a>
                    </div>

                    <p class="idsk-body idsk-body-hero">
                        {{ bigArticle.teaser| cms_document_links | raw }}
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="govuk-grid-row">

        {% for article in articles %}
            <div class="govuk-grid-column-one-third">
                {{ include('@ScoreCms/Public/default/_article_card_small.html.twig',{'article':article}) }}
            </div>
        {% endfor %}
    </div>
{% endif %}

src/Resources/views/Public/default/article_list.html.twig
{% extends cms_template() %}

{% block title %}
	{{ 'score.article.public.listTitle'|trans }}	|	{{parent()}}
{%
endblock %}

{% block body %}
	<div class="container py-3">
		{%  for row in articleList %}
			<div class="row govuk-grid-row">
				{% for article in row %}
					<div class="col-md-4 govuk-grid-column-one-third-from-desktop">
						{{ include('@ScoreCms/Public/default/_article_card_small.html.twig',{'article':article}) }}
					</div>
				{% endfor %}
			</div>
		{% endfor %}

		<div class="row">
			<div class="col">
				{{ include('@ScoreBase/Default/pager.html.twig', { 'pager': pager}) }}
			</div>
		</div>
	</div>
{% endblock %}

src/Resources/views/Public/default/documents.html.twig
{% extends cms_template() %}


{% block title %}
	{{"Dokumenty"}}	|	{{parent()}}
{% endblock %}

{% block javascripts %}

	{{parent()}}

{% endblock %}

{% block body %}
	<div class="container py-3">
		<div class="row">
			<div class="col-sm-12">
				{{ include('@ScoreCms/Public/default/documents_block.html.twig') }}
			</div>
		</div>		
	</div>
{% endblock %}

src/Resources/views/Public/default/subpage.html.twig
{# {% extends  template is defined and template is not null ? [template, '@ScoreCms/Page/Public/baseLayout.html.twig'] : '@ScoreCms/Page/Public/baseLayout.html.twig' %} #}
{% extends cms_template() %}
{% import "@ScoreBase/Default/macros.html.twig" as m %}
{% set reactFiles = cms_react_apps(page.blockJoints|map(pb => pb.block.type)) %}

{% macro getCenterClassNames(p) %}{{
	p.hasLeftBar and p.hasRightBar
		? "govuk-grid-column-full govuk-grid-column-one-half-from-desktop"
		: p.hasLeftBar or p.hasRightBar
			? "govuk-grid-column-full govuk-grid-column-three-quarters-from-desktop"
			: "govuk-grid-column-full"
 }}{% endmacro %}

{% block title %}{{page.title}} | {{parent()}} {% endblock %}

{% block stylesheets %}
	{{ page.metatags | filter (mTag => mTag.metatagPattern.type is same as "head") | join("\n") | raw }}
	{{ m.filterCss(reactFiles) }}
	{{parent()}}
{% endblock %}

{% block javascripts %}
{{ m.filterJs(reactFiles) }}
	{{parent()}}
{% endblock %}

 {% block footer_logo %}
	{{ 'idsk-footer-logo' | cms_text | raw  }}
 {% endblock %}

{% block body %}


	<div class="container{{ page_container_fluid is defined and page_container_fluid ? "-fluid" }} cms_seo_{{ page.seoId | replace({'/': "_"}) }}"> {# you can set in fwig globals #}
		<div class="row govuk-grid-row">
			<div class="col-md-12 govuk-grid-column-full">
				{% if not (hide_pages_heading is defined and hide_pages_heading) %} {# you can set in fwig globals #}
					<h1 class="govuk-heading-xl">{{ page.name }}</h1>
				{% endif %}
				{% if  page.seoId == 'homepage' and not (hide_homepage_intro_block is defined and hide_homepage_intro_block) %} {# you can set in fwig globals #}
					{{ include('@ScoreCms/Public/idsk/_intro_block.html.twig') }}
				{% endif %}
			</div>
		</div>
		<div class="{{page.layout}} row govuk-grid-row">

			{% if page.hasLeftBar %}
				<div class="col-md-12 col-lg-3 govuk-grid-column-full govuk-grid-column-one-quarter-from-desktop">
					{% for blockJoint in page.blockJoints %}
						{% if 'left' == blockJoint.place %}
							{# <h2>{{ blockJoint.block.name }}</h2> #}
							{{ include('@ScoreCms/Public/default/_block.html.twig',{'blockJoint': blockJoint}) }}
						{% endif %}
					{% endfor %}
				</div>
			{% endif %}

			<div class="col {{  _self.getCenterClassNames(page) }}">
			{% for blockJoint in page.blockJoints %} {# sections for wavex #}
				{% if 'center' == blockJoint.place %}
					<div id="cms-block-{{ blockJoint.block.id }}" class="{{ blockJoint.block.paramsArr.nav is defined and blockJoint.block.paramsArr.nav ? "section "}} cms-block-c-{{ blockJoint.block.id }}">
						{% if 'pageContent' == blockJoint.block.type %}
							{{ page.content| cms_document_links | raw }}
						{% else %}
							{# <h2>{{ blockJoint.block.name }}</h2>#}
							{{ include('@ScoreCms/Public/default/_block.html.twig',{'blockJoint': blockJoint}) }}
						{% endif %}
					</div>
				{% endif %}
			{% endfor %}
			</div>

			{% if page.hasRightBar %}
				<div class="col-md-12  col-lg-3 govuk-grid-column-full govuk-grid-column-one-quarter-from-desktop">
					{% for blockJoint in page.blockJoints %}
						{% if 'right' == blockJoint.place %}
						{# 	<h2>{{ blockJoint.block.name }}</h2>#}
							{{ include('@ScoreCms/Public/default/_block.html.twig',{'blockJoint': blockJoint}) }}
						{% endif %}
					{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}